# gwul/sfm-base:2.4.0
FROM gwul/sfm-base@sha256:dc6f305631f756d9c25517b6322ec83a024c11c3e1e1d7be742d74a57b1f1028
MAINTAINER Social Feed Manager <sfm@gwu.edu>

ENV GECKODRIVER_VER v0.30.0
RUN apt-get update && apt-get install -y \
    wget \
    iceweasel \
    xvfb
RUN set -x \
   && curl -sSLO https://github.com/mozilla/geckodriver/releases/download/${GECKODRIVER_VER}/geckodriver-${GECKODRIVER_VER}-linux64.tar.gz \
   && tar zxf geckodriver-*.tar.gz \
   && mv geckodriver /usr/bin/

ADD . /opt/sfm-test/
WORKDIR /opt/sfm-test
RUN pip install -r requirements/smoke_requirements.txt
CMD appdeps.py --wait-secs 180 --port-wait mq:5672 --port-wait ui:8080 \
    && python -m unittest discover
