FROM gwul/sfm-base@sha256:57882ae7eef059a36cb2df00a4e62d698fdf9a48535dd1120e501f2886f60cc9
MAINTAINER Justin Littman <justinlittman@gwu.edu>

RUN apt-get update && apt-get install -y \
    wget \
    iceweasel \
    xvfb

ADD . /opt/sfm-test/
WORKDIR /opt/sfm-test
RUN pip install -r requirements/smoke_requirements.txt
CMD appdeps.py --wait-secs 90 --port-wait mq:5672 --port-wait ui:8080 \
    && python -m unittest discover
