version: "2"
services:
    smoketests:
        image: gwul/sfm-docker-smoke:t1082
        links:
            - mq:mq
            - ui:ui
        environment:
            - TZ
            - DEBUG
            - SFM_RABBITMQ_USER
            - SFM_RABBITMQ_PASSWORD
